---
model_name: vitsimilaritymodel

# default seeds = 689
training_seeds: 689

# default use_cuda = true
use_cuda: true

# default epochs = 10
epochs: 10

# gradient clipping params
gradient_clipping: true
gradient_clipping_norm_value = 1.5

# default batch_size = 4
data_batch_size: 4

# default learning_rate = 0.001
learning_rate: 0.001

preprocessing:
    resize: 256
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

use_cuda: true

