---
model_name: vitsimilaritymodel

# default seeds = 689
training_seeds: 689

# default use_cuda = true
use_cuda: true

# default epochs = 8
epochs: 8

# gradient clipping params
gradient_clipping: false
gradient_clipping_norm_value: 1.25

# default batch_size = 4
data_batch_size: 4

# default learning_rate = 0.001
learning_rate: 0.001

preprocessing:

use_cuda: true

